[package]
name = "compilation-killer"
version = "0.1.0"
authors = ["EarvinKayonga <demoneartin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[profile.release]
lto = "fat"
codegen-units = 1
